//! Settings page (mirrors the original SettingsPage, trimmed per requirements:
//! 通用 / 加速 / 关于. Plugin and Steam settings removed.)

use crate::App;
use eframe::egui;
use std::sync::LazyLock;
use wtlite_core::model::ProxyMode;

/// Secondary-development repository link (to be filled in by the author).
pub const SECONDARY_REPO_URL: &str = "https://github.com/s13mjl/WattToolkit-Lite";

/// Upstream project link.
pub const UPSTREAM_REPO_URL: &str = "https://github.com/BeyondDimension/SteamTools";

/// Static icon image (recolor of the original accelerator icon).
pub static APP_ICON: LazyLock<Option<egui::ColorImage>> = LazyLock::new(load_icon);

fn load_icon() -> Option<egui::ColorImage> {
    // The icon PNG is generated by the loader at startup (recolor of the original ico).
    let path = wtlite_core::paths::cache_dir().join("icon.png");
    let bytes = std::fs::read(path).ok()?;
    let img = image::load_from_memory(&bytes).ok()?;
    let rgba = img.to_rgba8();
    let (w, h) = (rgba.width() as usize, rgba.height() as usize);
    Some(egui::ColorImage::from_rgba_unmultiplied([w, h], &rgba))
}

#[derive(PartialEq, Eq, Clone, Copy)]
pub enum SettingsTab {
    General,
    Accelerate,
    About,
}

pub static SETTINGS_TAB: LazyLock<std::sync::Mutex<SettingsTab>> =
    LazyLock::new(|| std::sync::Mutex::new(SettingsTab::General));

pub fn show(app: &mut App, ui: &mut egui::Ui) {
    let mut tab = *SETTINGS_TAB.lock().unwrap();
    crate::pages::hrow(ui, |ui| {
        if crate::pages::tab_btn(ui, tab == SettingsTab::General, "通用") {
            tab = SettingsTab::General;
        }
        if crate::pages::tab_btn(ui, tab == SettingsTab::Accelerate, "加速") {
            tab = SettingsTab::Accelerate;
        }
        if crate::pages::tab_btn(ui, tab == SettingsTab::About, "关于") {
            tab = SettingsTab::About;
        }
    });
    *SETTINGS_TAB.lock().unwrap() = tab;
    ui.separator();
    ui.add_space(6.0);

    egui::ScrollArea::vertical().show(ui, |ui| {
        match tab {
            SettingsTab::General => general_tab(app, ui),
            SettingsTab::Accelerate => accelerate_tab(app, ui),
            SettingsTab::About => about_tab(app, ui),
        }
    });
}

fn general_tab(app: &mut App, ui: &mut egui::Ui) {
    let mut ar_changed = false;
    {
        let g = &mut app.settings.general;
        ui.checkbox(&mut g.auto_check_app_update, "启动时自动检查更新");
        let mut ar = g.auto_run_on_startup;
        if ui.checkbox(&mut ar, "开机自动启动").changed() {
            g.auto_run_on_startup = ar;
            ar_changed = true;
        }
        ui.checkbox(&mut g.minimize_on_startup, "启动时最小化到托盘");
        ui.checkbox(&mut g.tray_icon, "显示托盘图标");
        ui.checkbox(&mut g.gpu, "使用 GPU 加速渲染");
    }
    if ar_changed {
        let ar = app.settings.general.auto_run_on_startup;
        match wtlite_core::settings::set_auto_run_on_startup(ar) {
            Ok(()) => app.set_toast("开机自启动设置已更新"),
            Err(e) => app.set_toast(format!("开机自启动设置失败: {e}")),
        }
    }
    ui.add_space(8.0);
    if ui.button("保存").clicked() {
        let r = app.settings.save();
        app.set_toast(match r {
            Ok(()) => "设置已保存".to_string(),
            Err(e) => format!("保存失败: {e}"),
        });
    }
}

fn accelerate_tab(app: &mut App, ui: &mut egui::Ui) {
    let p = &mut app.settings.proxy;
    ui.heading("默认加速设置");
    let mode_label = p.proxy_mode.display_name().to_string();
    crate::pages::hrow(ui, |ui| {
        ui.label("默认加速模式:");
        if ui.selectable_label(false, mode_label).clicked() {
            let avail = ProxyMode::available();
            let idx = avail.iter().position(|m| *m == p.proxy_mode).unwrap_or(0);
            p.proxy_mode = avail[(idx + 1) % avail.len()];
        }
        ui.label(format!("({})", p.proxy_mode.as_str()));
    });
    ui.checkbox(&mut p.program_startup_run_proxy, "程序启动时自动运行加速");
    ui.checkbox(&mut p.enable_http_proxy_to_https, "允许 HTTP 请求转发为 HTTPS");
    ui.checkbox(&mut p.is_enable_script, "启用加速脚本");
    ui.add_space(8.0);
    if ui.button("保存").clicked() {
        let r = app.settings.save();
        app.set_toast(match r {
            Ok(()) => "设置已保存".to_string(),
            Err(e) => format!("保存失败: {e}"),
        });
    }
}

fn about_tab(app: &App, ui: &mut egui::Ui) {
    crate::pages::vcenter(ui, |ui| {
        if let Some(handle) = app.icon.as_ref() {
            let s = 64.0;
            let img = egui::Image::from_texture(handle)
                .maintain_aspect_ratio(true)
                .max_size(egui::vec2(s, s));
            ui.add(img);
        }
        ui.add_space(6.0);
        ui.strong("WattToolkit-Lite");
        ui.label(format!("版本 {}", wtlite_core::APP_VERSION));
    });
    ui.add_space(12.0);
    crate::pages::hrow(ui, |ui| {
        ui.label("许可证:");
        ui.label("GPL-3.0-or-later");
    });
    crate::pages::hrow(ui, |ui| {
        ui.label("上游项目:");
        ui.hyperlink(UPSTREAM_REPO_URL);
    });
    crate::pages::hrow(ui, |ui| {
        ui.label("二次开发:");
        ui.hyperlink(SECONDARY_REPO_URL);
    });
    ui.add_space(12.0);
    ui.label("WattToolkit-Lite 是一个仅复现 WattToolkit 网络加速与设置功能的二次开发项目（Windows）。");
}
